# Generated by Django 2.1.3 on 2018-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='title',
            field=models.CharField(default='Przelew', max_length=50),
        ),
    ]
